export const MAKE_ORDER_REQUEST: "MAKE_ORDER_REQUEST" = "MAKE_ORDER_REQUEST";
export const MAKE_ORDER_SUCCESS: "MAKE_ORDER_SUCCESS" = "MAKE_ORDER_SUCCESS";
export const MAKE_ORDER_FAILED: "MAKE_ORDER_FAILED" = "MAKE_ORDER_FAILED";
export const MAKE_ORDER_TOGGLE_MODAL: "MAKE_ORDER_TOGGLE_MODAL" =
  "MAKE_ORDER_TOGGLE_MODAL";
